### ISSUE TITLE
Not working with PR from fork

### ISSUE THREAD

**Issue by mbrodala** [tibdex/github-app-token#25]
https://github.com/tibdex/backport/issues/33 recommends setting up this action job to work around the limitations of the `GITHUB_TOKEN`.

However, it seems like the same limitation applies to an app ID and client secret if it is injected via (organisation) secrets:

> Secrets are not passed to workflows that are triggered by a pull request from a fork. [Learn more](https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

So, how is this supposed to work exactly?

**Comment by mbrodala** [comment]
Here are 2 commits where I tried to set this up:

https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/03f75bff044e62a0e39ee801f0828bb404a3c3fc
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/88b91e3f1dd7e0dbf7d49a93350b9db7a086a7f0

The current `.github/workflows.backport.yml`:

```yaml
name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BACKPORT_APP_ID }}
          private_key: ${{ secrets.BACKPORT_APP_SECRET }}
      - name: Backport
        uses: tibdex/backport@v1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
```

The `BACKPORT_APP_ID` and `BACKPORT_APP_SECRET` have been set in the organisation secrets.

The result: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1552/checks?check_run_id=3825926413

```
Run tibdex/github-app-token@v1
  with:
Error: Error: Input required and not supplied: app_id
```
