### ISSUE TITLE
Error: HttpError: Not Found

### ISSUE THREAD

**Issue by savnik** [tibdex/github-app-token#27]
When using the bare minimum example i get following error:
```
Error: HttpError: Not Found
```

I think that might relates to the GITHUB_API_URL in the fetch request?

Code:
```yml
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
```
