### ISSUE TITLE
Workflow still not running with Labeler

### ISSUE THREAD

**Issue by beefchimi** [tibdex/github-app-token#31]
I seem to have no success with `github_app-token` + [`labeler`](https://github.com/actions/labeler). Here is my workflow:

```yml
name: Labeler
on: [pull_request_target]

jobs:
  triage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - name: Generate unique app token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.SPECIAL_APP_ID }}
          private_key: ${{ secrets.SPECIAL_APP_PRIVATE_KEY }}

      - name: Apply PR labels
        uses: actions/labeler@v3
        with:
          repo-token: ${{ steps.generate-token.outputs.token }}
```

`labeler` runs perfectly whenever a PR is put up by a contributor. But, if `github-actions` opens a PR, this check is never run. The one workflow triggering the effected PR is [`changesets/action@v1`](https://github.com/changesets/action).

I'm curious if anyone else has run into this? Perhaps this is an issue with `pull_request_target` and/or `permissions`?

Any help is appreciated!
