### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by teoljungberg** [tibdex/github-app-token#4]
👋 

We're using tibdex/autosquash at my company and are _very_ happy with it. It's setup to use a the personal access token of a shared account we have, sadly that account is so broadly used that it is using up a lot of our access tokens and gets rate limited often enough that it is starting to become an annoyance.

In my research - I found this repository and wondered how I would go about setting this up, and if it would resolve our issue?

With the abundance of options to setup a new GitHub App I was a bit stunned to say the least, is there a default set of options that needs to be setup that you could share?

**Comment by tibdex** [comment]
Hi Teo, if you're getting range limited using a personal access token you will probably get rate limited too with a GitHub App. Maybe you could reach out to GitHub to buy more credits?

Here is how I use `github-app-token` with Autosquash:

```
name: Autosquash
on:
  check_run:
    types: [completed]
  pull_request:
    types: [closed, labeled]
  pull_request_review:
    types: [submitted]
  status: {}

jobs:
  autosquash:
    runs-on: ubuntu-18.04
    name: Autosquash
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: tibdex/autosquash@v2
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
```
