### ISSUE TITLE
Question: not working with my current set-up?

### ISSUE THREAD

**Issue by Khaaz** [tibdex/github-app-token#53]
1) Does this action works and allows to replace a personnal access token with a github app token in every situation? Or are there limitations when using this action?

2) In my current setup I have an action to automatically merge dependabot MR.

I have added the github app `app_id` as `GH_APP_ID` in the repository action secrets, and I have generated a private key in my app. I have added the key in its entirety (including the BEGIN RSA and END RSA) as `GH_APP_KEY` also in the repository action secrets.

However, when running this action, I get the following error at the github-app-token generating key step:
` Error: Input required and not supplied: private_key`

Here is the code for the action.
```yaml
name: Dependabot-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GH token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PKEY }}
      - uses: actions/checkout@v3
      - name: Automerge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.generate_token.outputs.token }}
```

What am I doing wrong?

I also want to highlight that for some reason, it "almost" works with another action I have. The error is different though: here the [link](https://github.com/BetaHuhn/repo-file-sync-action/discussions/283) to the issue in the other action repository. 

Thanks in advance
