### ISSUE TITLE
Action fails on ubuntu-jammy runner

### ISSUE THREAD

**Issue by Ravio1i** [tibdex/github-app-token#54]
## Description
When using the action on a github runner with ubuntu-jammy (22.04) it fails with:

## Error

```bash
Error: Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library
```

## Usage
```yaml
jobs:
    build:
    runs-on: ubuntu-jammy
        steps:
          - name: Generate token from github app
            id: generate_token
            uses: tibdex/github-app-token@v1.7
            with:
              app_id: ${{ secrets.APP_ID }}
              private_key: ${{ secrets.APP_KEY }}
```

## References

- https://github.com/nodejs/node/discussions/43184

**Comment by Eran-BenShahar** [comment]
I'm also getting this error, when will the fix be merged?
Or is there any other workaround?

**Comment by prein** [comment]
@hamnis is there a way to use the action from your fork? I wanted to see if it fixes the issue for me

**Comment by hamnis** [comment]
Seems like this should be possible: https://stackoverflow.com/a/68286342

**Comment by prein** [comment]
> Seems like this should be possible: https://stackoverflow.com/a/68286342

Thanks for looking it up for me. This way I tried first and it didn't work producing the following error
```
File not found: '/runner/_work/_actions/hamnis/github-app-token/upgrade-octocat-auth-app/dist/index.js'
```
I tried branch, sha, and local copy - it needs to be compiled like you said in your other reply.

**Comment by hamnis** [comment]
@prein try using the [upgrade-octocat-auth-app-dist](https://github.com/hamnis/github-app-token/tree/upgrade-octocat-auth-app-dist) branch

**Comment by jazzlyn** [comment]
@hamnis I tried with your reference, still same error.

it seems this is an issue with node 16 and openssl, see https://stackoverflow.com/questions/72104449/node-js-crypto-fails-to-sign-pem-key-string-from-file-with-error25066067dso-su fixe

```yaml
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        env:
          OPENSSL_CONF: /dev/null
```
fixed it for me.

**Comment by prein** [comment]
@jazzlyn thanks for sharing! It worked for me too

@hamnis I got it to run with the action compiled locally, but got a different error
```
Error: secretOrPrivateKey must be an asymmetric key when using RS256
```
<details>
  <summary>Sharing the code just for completeness</summary>

```
     - name: Get github-app-token action from forked repo
       uses: actions/checkout@v3
       with:
         repository: hamnis/github-app-token
         ref: upgrade-octocat-auth-app
         path: hamnis-github-app-token
     # Compile the action to be able to use it
     - uses: actions/setup-node@v3
       with:
         node-version: latest
     - name: Install Yarn
       run: npm install -g yarn
     - name: Install
       run: yarn install --frozen-lockfile
       working-directory: hamnis-github-app-token
     - name: Deduplicate dependencies
       run: yarn run yarn-deduplicate --fail --strategy fewer
       working-directory: hamnis-github-app-token
     - name: Build
       run: yarn run build
       working-directory: hamnis-github-app-token
     - name: Format
       run: yarn run prettier --check
       working-directory: hamnis-github-app-token
     - name: Lint
       run: yarn run xo
       working-directory: hamnis-github-app-token
     # action should now be compiled, we can use it like this:
     - name: Generate app token
       id: generate_token
       uses: ./hamnis-github-app-token
       with:
         app_id: ${{ inputs.gh_app_id }}
         private_key: ${{ inputs.gh_app_private_key }}
```
</details>
