### ISSUE TITLE
How to upgrade from v1 to v2?

### ISSUE THREAD

**Issue by josephjthomas** [tibdex/github-app-token#94]
I have the following code in my workflow:
```yaml
steps:
      - uses: tibdex/github-app-token@v1
        id: get-token
        with:
          app_id: ${{ secrets.a }}
          private_key: ${{ secrets.b }}
          repository: example/repository
```
How would I update that to v2 of the action? I took a look at the readme, but it looks like the scopes changes?
